[package]
name = "shim-interface"
version = "0.1.0"
description = "A library to provide service interface of Kata Containers"
keywords = ["kata", "container", "http"]
categories = ["services"]
authors = ["The Kata Containers community <kata-dev@lists.katacontainers.io>"]
repository = "https://github.com/kata-containers/kata-containers.git"
homepage = "https://katacontainers.io/"
license = "Apache-2.0"
edition = "2018"

[dependencies]
kata-types = { path = "../kata-types" }
