//
// Copyright (c) 2017 HyperHQ Inc.
// Copyright (c) 2019-2020 Ant Group
//
// SPDX-License-Identifier: Apache-2.0
//

syntax = "proto3";

option go_package = "github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/agent/protocols/grpc";

package grpc;

import "google/protobuf/empty.proto";

message CheckRequest {
	string service = 1;
}

message VersionCheckResponse {
	string grpc_version = 1;
	string agent_version = 2;
}

service Health {
	rpc Check(CheckRequest) returns (google.protobuf.Empty);
	rpc Version(CheckRequest) returns (VersionCheckResponse);
}
