// Copyright (c) 2019-2023 Alibaba Cloud
// Copyright (c) 2019-2023 Ant Group
//
// SPDX-License-Identifier: Apache-2.0
//

use std::{collections::HashMap, convert::TryFrom, sync::Arc};

use anyhow::{anyhow, Context, Result};
use kata_sys_util::rand::RandomBytes;
use kata_types::config::hypervisor::BlockDeviceInfo;
use tokio::sync::{Mutex, RwLock};

use crate::{
    BlockConfigModern, BlockDeviceModernHandle, Hypervisor, NetworkDevice, KATA_MMIO_BLK_DEV_TYPE,
    VIRTIO_BLOCK_MMIO,
};

use super::{
    util::{get_host_path, get_virt_drive_name, DEVICE_TYPE_BLOCK},
    Device, DeviceConfig, DeviceType,
};

pub type ArcMutexDevice = Arc<Mutex<dyn Device>>;

/// Available MMIO disk indices. Released slots are reused in ascending order.
#[derive(Clone, Debug, Default)]
struct SharedInfo {
    block_index: u64,
    released_block_index: Vec<u64>,
}

impl SharedInfo {
    fn declare_device_index(&mut self) -> Result<u64> {
        if let Some(index) = self.released_block_index.pop() {
            return Ok(index);
        }
        let index = self.block_index;
        self.block_index = index.checked_add(1).context("block index overflow")?;
        Ok(index)
    }

    fn release_device_index(&mut self, index: u64) {
        self.released_block_index.push(index);
        self.released_block_index.sort_by(|a, b| b.cmp(a));
    }
}

// Device manager will manage the lifecycle of sandbox device
#[derive(Debug)]
pub struct DeviceManager {
    devices: HashMap<String, ArcMutexDevice>,
    hypervisor: Arc<dyn Hypervisor>,
    shared_info: SharedInfo,
}

impl DeviceManager {
    pub async fn new(hypervisor: Arc<dyn Hypervisor>) -> Result<Self> {
        let devices = HashMap::<String, ArcMutexDevice>::new();
        Ok(DeviceManager {
            devices,
            hypervisor,
            shared_info: SharedInfo::default(),
        })
    }

    async fn get_block_device_info(&self) -> BlockDeviceInfo {
        self.hypervisor.hypervisor_config().await.blockdev_info
    }

    async fn try_add_device(&mut self, device_id: &str) -> Result<()> {
        // find the device
        let device = self
            .devices
            .get(device_id)
            .context("failed to find device")?;

        let mut device_guard = device.lock().await;
        // attach device
        let result = device_guard.attach(self.hypervisor.as_ref()).await;
        // handle attach error
        if let Err(e) = result {
            match device_guard.get_device_info().await {
                DeviceType::BlockModern(device) => {
                    let index = device.lock().await.config.index;
                    self.shared_info.release_device_index(index);
                }
                _ => {
                    debug!(sl!(), "no need to do release device index.");
                }
            }

            drop(device_guard);
            self.devices.remove(device_id);

            return Err(e);
        }

        Ok(())
    }

    pub async fn try_remove_device(&mut self, device_id: &str) -> Result<()> {
        if let Some(dev) = self.devices.get(device_id) {
            let mut device_guard = dev.lock().await;
            if let Some(index) = device_guard.detach().await? {
                // Other containers may still refer to the same drive. Release
                // the slot and its lookup entry only after the last reference.
                self.shared_info.release_device_index(index);
                drop(device_guard);
                self.devices.remove(device_id);
            }
            return Ok(());
        }

        Err(anyhow!(
            "device with specified ID hasn't been created. {}",
            device_id
        ))
    }

    async fn get_device_info(&self, device_id: &str) -> Result<DeviceType> {
        if let Some(dev) = self.devices.get(device_id) {
            return Ok(dev.lock().await.get_device_info().await);
        }

        Err(anyhow!(
            "device with specified ID hasn't been created. {}",
            device_id
        ))
    }

    async fn find_device(&self, host_path: String) -> Option<String> {
        for (device_id, dev) in &self.devices {
            match dev.lock().await.get_device_info().await {
                DeviceType::Network(device) => {
                    if device.config.host_dev_name == host_path {
                        return Some(device_id.to_string());
                    }
                }

                DeviceType::BlockModern(device) => {
                    if device.lock().await.config.path_on_host == host_path {
                        return Some(device_id.to_string());
                    }
                }
            }
        }

        None
    }

    async fn new_device(&mut self, device_config: &DeviceConfig) -> Result<String> {
        // device ID must be generated by manager instead of device itself
        // in case of ID collision
        let device_id = self.new_device_id()?;
        let dev: ArcMutexDevice = match device_config {
            DeviceConfig::BlockCfgModern(config) => {
                anyhow::ensure!(
                    config.driver_option == VIRTIO_BLOCK_MMIO,
                    "kata-fc-minimal: unsupported block transport {}",
                    config.driver_option
                );

                if let Some(device_matched_id) = self.find_device(config.path_on_host.clone()).await
                {
                    return Ok(device_matched_id);
                }

                self.create_block_device_modern(config, device_id.clone())
                    .await
                    .context("failed to create block device modern")?
            }

            DeviceConfig::NetworkCfg(config) => {
                // try to find the device, found and just return id.
                let host_path = config.host_dev_name.as_str();
                if let Some(dev_id_matched) = self.find_device(host_path.to_owned()).await {
                    info!(
                        sl!(),
                        "network device with path:{:?} found. return network device id: {:?}",
                        host_path,
                        dev_id_matched
                    );

                    return Ok(dev_id_matched);
                }

                Arc::new(Mutex::new(NetworkDevice::new(device_id.clone(), config)))
            }
        };

        // register device to devices
        self.devices.insert(device_id.clone(), dev.clone());

        Ok(device_id)
    }

    async fn create_block_device_modern(
        &mut self,
        config: &BlockConfigModern,
        device_id: String,
    ) -> Result<ArcMutexDevice> {
        let mut block_config = config.clone();
        block_config.driver_option = KATA_MMIO_BLK_DEV_TYPE.to_string();
        let index = self.shared_info.declare_device_index()?;
        block_config.index = index;
        block_config.virt_path = format!("/dev/{}", get_virt_drive_name(i32::try_from(index)?)?);

        if block_config.path_on_host.is_empty() {
            block_config.path_on_host =
                get_host_path(DEVICE_TYPE_BLOCK, config.major, config.minor)
                    .context("failed to get host path")?;
        }

        Ok(Arc::new(Mutex::new(BlockDeviceModernHandle::new(
            device_id,
            block_config,
        ))))
    }

    // device ID must be generated by device manager instead of device itself
    // in case of ID collision
    fn new_device_id(&self) -> Result<String> {
        for _ in 0..5 {
            let rand_bytes = RandomBytes::new(8);
            let id = format!("{rand_bytes:x}");

            // check collision in devices
            if !self.devices.contains_key(&id) {
                return Ok(id);
            }
        }

        Err(anyhow!("ID are exhausted"))
    }
}

// Many scenarios have similar steps when adding devices. so to reduce duplicated code,
// we should create a common method abstracted and use it in various scenarios.
// do_handle_device:
// (1) new_device with DeviceConfig and return device_id;
// (2) try_add_device with device_id and do really add device;
// (3) return device info of device's info;
pub async fn do_handle_device(
    d: &RwLock<DeviceManager>,
    dev_info: &DeviceConfig,
) -> Result<DeviceType> {
    let device_id = d
        .write()
        .await
        .new_device(dev_info)
        .await
        .context("failed to create device")?;

    d.write()
        .await
        .try_add_device(&device_id)
        .await
        .context("failed to add device")?;

    let device_info = d
        .read()
        .await
        .get_device_info(&device_id)
        .await
        .context("failed to get device info")?;

    Ok(device_info)
}

pub async fn get_block_device_info(d: &RwLock<DeviceManager>) -> BlockDeviceInfo {
    d.read().await.get_block_device_info().await
}

#[cfg(test)]
mod tests {
    use super::{DeviceManager, SharedInfo};
    use crate::{
        device::{device_manager::get_block_device_info, DeviceConfig, DeviceType},
        firecracker::Firecracker,
        BlockConfigModern, KATA_MMIO_BLK_DEV_TYPE, VIRTIO_BLOCK_MMIO,
    };
    use anyhow::{Context, Result};
    use std::sync::Arc;
    use tokio::sync::RwLock;

    async fn new_device_manager() -> Result<Arc<RwLock<DeviceManager>>> {
        let mut config = kata_types::config::Hypervisor::default();
        config.blockdev_info.block_device_driver = "virtio-blk-mmio".into();
        let hypervisor = Firecracker::new();
        hypervisor.set_hypervisor_config(config).await;

        let dm = Arc::new(RwLock::new(
            DeviceManager::new(Arc::new(hypervisor))
                .await
                .context("device manager")?,
        ));

        Ok(dm)
    }

    #[test]
    fn released_mmio_indices_are_reused_without_skipping_fresh_slots() {
        let mut info = SharedInfo::default();
        assert_eq!(info.declare_device_index().unwrap(), 0);
        assert_eq!(info.declare_device_index().unwrap(), 1);
        info.release_device_index(1);
        info.release_device_index(0);
        assert_eq!(info.declare_device_index().unwrap(), 0);
        assert_eq!(info.declare_device_index().unwrap(), 1);
        assert_eq!(info.declare_device_index().unwrap(), 2);
    }

    #[actix_rt::test]
    async fn test_new_block_device() {
        let dm = new_device_manager().await;
        assert!(dm.is_ok());

        let d = dm.unwrap();
        let block_driver = get_block_device_info(&d).await.block_device_driver;
        let dev_info = DeviceConfig::BlockCfgModern(BlockConfigModern {
            path_on_host: "/dev/dddzzz".to_string(),
            is_readonly: true,
            driver_option: block_driver,
            ..Default::default()
        });
        let new_device_result = d.write().await.new_device(&dev_info).await;
        assert!(new_device_result.is_ok());

        let device_id = new_device_result.unwrap();
        let devices_info_result = d.read().await.get_device_info(&device_id).await;
        assert!(devices_info_result.is_ok());

        let device_info = devices_info_result.unwrap();
        if let DeviceType::BlockModern(device_lock) = device_info {
            let device = device_lock.lock().await;
            assert_eq!(device.config.driver_option, KATA_MMIO_BLK_DEV_TYPE);
            assert_eq!(device.config.virt_path, "/dev/vda");
            assert!(device.config.is_readonly);
        } else {
            panic!("expected an MMIO block device")
        }
    }

    #[tokio::test]
    async fn shared_block_device_remains_registered_until_last_detach() {
        let dm = new_device_manager().await.unwrap();
        let mut dm = dm.write().await;
        let id = dm
            .new_device(&DeviceConfig::BlockCfgModern(BlockConfigModern {
                path_on_host: "/dev/shared-test".into(),
                driver_option: VIRTIO_BLOCK_MMIO.into(),
                ..Default::default()
            }))
            .await
            .unwrap();
        let DeviceType::BlockModern(device) = dm.get_device_info(&id).await.unwrap() else {
            panic!("expected block device");
        };
        device.lock().await.attach_count = 2;
        dm.try_remove_device(&id).await.unwrap();
        assert!(dm.get_device_info(&id).await.is_ok());
        assert_eq!(device.lock().await.attach_count, 1);
        assert_eq!(dm.shared_info.declare_device_index().unwrap(), 1);
        dm.try_remove_device(&id).await.unwrap();
        assert!(dm.get_device_info(&id).await.is_err());
        assert_eq!(dm.shared_info.declare_device_index().unwrap(), 0);
    }

    #[tokio::test]
    async fn unsupported_transports_do_not_enter_manager() {
        let dm = new_device_manager().await.unwrap();
        let mut dm = dm.write().await;
        for driver in [
            "virtio-blk-pci",
            "virtio-blk-ccw",
            "virtio-scsi",
            "virtio-pmem",
        ] {
            let config = DeviceConfig::BlockCfgModern(BlockConfigModern {
                driver_option: driver.into(),
                path_on_host: "/dev/unsupported".into(),
                ..Default::default()
            });
            assert!(dm
                .new_device(&config)
                .await
                .unwrap_err()
                .to_string()
                .contains("unsupported block transport"));
            assert!(dm.devices.is_empty());
            assert_eq!(dm.shared_info.block_index, 0);
        }
    }
}
